cloudflare-token: ENC[AES256_GCM,data:XinkIVBTi1T+IMtmhXiNeBNY00v4ySMnGYhJ7YQ7J9YBiY8IoZ2D22rtVQiK4Fz2pa9v26Va5NYdtE8yiK04sww9eg3myZmLe06D3kyehA270kV31SOezU4YJ6DcyTm0KTfBFnhCjnKv1jNfrROLkUDhrxVigAIrOdeltMgMI6EzXePq81eAF3vQeI+W4fK41JNg2DVmiJmTi3A8QsCTR38GTdrdMEWdWkB+mBrOakuFQIzQZc8rEdjm8HMYqrgHIjuZIJM=,iv:IEmLNR2ZeIb+hhS1DlXlOkbltLS4mwMxkyAf35k4NOg=,tag:R/2Y72ccV+JtS0OnIxm7Zg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY3dhQXdrVEE3eldrSWV6
            MU4vRHJBeWtBMEdFclhvZGdnQlAwcHRpSnljCktDSnpSTW44UENpQVNzT0l5OWp4
            UmZDTUErTUJVVk5JTWxMQnlRWGxJYmcKLS0tIEVLZDJwRTRvd1M0WHJUVUIyNzhp
            NW15UkFpcDZMZ1FmOW8wKzlPVE9TUncK9bmtLkC4vi97AooF5A4YV4NjCeaHkfNp
            kHyoOXeAEvwV7VrGQk4qontdFxTwlj3/V0i5YCd06ZB10xu8Zd0A/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10fylukdnxx3r9vyz8zkvur64u3drw0m4w2krgadzusnvazzwqgcskdrwvs
    lastmodified: "2026-06-16T03:26:43Z"
    mac: ENC[AES256_GCM,data:0gk4NIGIof8h6L64zr3cp5TJbCQXrx57Ot+VM41BYGfEEjlvuVsh+5k4dSmpJMdnLVmfUA9I4WK/UdG05IQUnp/oG/zsiLkagVQ3mI4pSeA/esQY7jkAP/LdgvMdjOZ9wAYJDzoU1ikm3cjsZHQ/r5ISFyIIMOrMdYIRBHxOSFM=,iv:GBAlQA6UQQesdxXe4TmuYOfqmRk24pLwrmqTbkIzMYI=,tag:2Gltm8Cmv+tac2uWncxlgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
