theinfinitewebsite_env: ENC[AES256_GCM,data:m/aQdRknTPTDkp1QcKoANEMAryfJD8gPJvYL/fjmFVA9INPjEo8OZkZ9xL2j/+8tVoGwUvdqB41XTUtPV52bd+YGtlTWVSCJyTMeciEQ0DK0BrRWEoNlN+mR8WTZivARwjmoi32odtYq2VxM0BWjYtQ9ua1mSQIKRlINiWXlTWBORyas14vH3X6qg6Dkz6X0fS3v1tO/QoXB7k69Y2C5myiCk2cRYCp11AFcdAXmqsI/XaKGVTGeZpLBx4wJdeiq8kLoArzb4AtpGw+V+8dITm6wiBLjTA20fjz8vfGH5YiqfPMjFfrM1LrY0P8RIhgfv0Ax0itoG1yeSoiU8TDdK7tt1mTVAMrBhP8WY5dbGpHIcNBy6YopGgIc17EuyU89iY+YMS1957VXBmo1wF5pvuMLK8oP5mpfoYL475lszcLcPjaW/9SUHv/BnP/gxtX3TXtJpUnXucCWaHO+floYJJT7C/g5isRY85nHqUM3yXNOTs9TSku2A6ySErqcdf2avg==,iv:5JEN2bnydoKbwuHjzRAivbwt0weF3SCqOFV34QJOEZU=,tag:lI61Jz7gcoyjIJQjkQw9Ng==,type:str]
sops:
    age:
        - recipient: age140vtdn6kd0mzm6r086xc24p2fq4rv4fh44lhelh60zr75d433s7svuvh77
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjS0Q5c01DT2tRUVlBRmZT
            Q052cStjdFdROFUzdW01MzNOVUw4MkxCYmlVCjVIb1RET05wVmRBYWZOUXNXeDc0
            aWhTMXlNNkFPYXF4TkVINVU3OGs5OG8KLS0tIFkyYnY0RDd5Y29hRFhPTTE4WmN5
            MjAwamI3ZXA4RVExRDNXWW1yWnA0bEEK+tG54ki02Ax8jdyJePMyRFYBjSHUzllh
            OXE/pK5+58Npzj57DGrsXhFSAs+GZrJGcgrBdWUWfmPOaZgjcNopQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T03:35:28Z"
    mac: ENC[AES256_GCM,data:MZqF15qxJsHZtT+b3QatRou+WCf9T5j/wKXezWwcsv//JcjydXuis8v5feqRe0xSYhIMtLFS8htnmwg3jvSaTRgOGAzOl0rVTa6U/R1NEjNDAj0DJ2qGsnAdgIRdvuaJvBPTFOol818uhj7OpFzpBS1nwQ6dI13WTVFcP7747XI=,iv:RsF6vpL7AUPaUNHY0WCR2ej4lRxeaui7sXvVSPNhFNM=,tag:C1AlEAd93fAXSGK9SwZeHg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
