# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."odysseus-chromadb" = {
    image = "docker.io/chromadb/chroma:latest";
    environment = {
      "ANONYMIZED_TELEMETRY" = "FALSE";
    };
    volumes = [
      "odysseus_chromadb-data:/chroma/chroma:rw"
    ];
    ports = [
      "127.0.0.1:8100:8000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=chromadb"
      "--network=odysseus_default"
    ];
  };
  systemd.services."docker-odysseus-chromadb" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-odysseus_default.service"
      "docker-volume-odysseus_chromadb-data.service"
    ];
    requires = [
      "docker-network-odysseus_default.service"
      "docker-volume-odysseus_chromadb-data.service"
    ];
    partOf = [
      "docker-compose-odysseus-root.target"
    ];
    wantedBy = [
      "docker-compose-odysseus-root.target"
    ];
  };
  virtualisation.oci-containers.containers."odysseus-ntfy" = {
    image = "docker.io/binwiederhier/ntfy";
    environment = {
      "NTFY_BASE_URL" = "http://localhost:8091";
    };
    volumes = [
      "odysseus_ntfy-cache:/var/cache/ntfy:rw"
    ];
    ports = [
      "127.0.0.1:8091:80/tcp"
    ];
    cmd = [ "serve" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=ntfy"
      "--network=odysseus_default"
    ];
  };
  systemd.services."docker-odysseus-ntfy" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-odysseus_default.service"
      "docker-volume-odysseus_ntfy-cache.service"
    ];
    requires = [
      "docker-network-odysseus_default.service"
      "docker-volume-odysseus_ntfy-cache.service"
    ];
    partOf = [
      "docker-compose-odysseus-root.target"
    ];
    wantedBy = [
      "docker-compose-odysseus-root.target"
    ];
  };
  virtualisation.oci-containers.containers."odysseus-odysseus" = {
    image = "compose2nix/odysseus-odysseus";
    environment = {
      "ALLOWED_ORIGINS" = "http://localhost,http://127.0.0.1";
      "AUTH_ENABLED" = "true";
      "CHROMADB_HOST" = "chromadb";
      "CHROMADB_PORT" = "8000";
      "CLEANUP_INTERVAL_HOURS" = "24";
      "DATABASE_URL" = "sqlite:///./data/app.db";
      "DATA_BRAVE_API_KEY" = "";
      "EMBEDDING_API_KEY" = "";
      "EMBEDDING_MODEL" = "";
      "EMBEDDING_URL" = "";
      "FASTEMBED_CACHE_PATH" = "";
      "FASTEMBED_MODEL" = "sentence-transformers/all-MiniLM-L6-v2";
      "GOOGLE_API_KEY" = "";
      "GOOGLE_PSE_CX" = "";
      "HF_TOKEN" = "";
      "HUGGING_FACE_HUB_TOKEN" = "";
      "LLM_HOST" = "host.docker.internal";
      "LLM_HOSTS" = "";
      "LOCALHOST_BYPASS" = "false";
      "NVIDIA_DRIVER_CAPABILITIES" = "compute,utility";
      "NVIDIA_VISIBLE_DEVICES" = "all";
      "ODYSSEUS_ADMIN_PASSWORD" = "";
      "ODYSSEUS_ADMIN_USER" = "admin";
      "ODYSSEUS_CHAT_UPLOAD_MAX_BYTES" = "10485760";
      "ODYSSEUS_INPROCESS_POLLERS" = "1";
      "ODYSSEUS_INPROCESS_TASKS" = "1";
      "ODYSSEUS_SCRIPT_HOST" = "localhost";
      "OLLAMA_BASE_URL" = "http://host.docker.internal:11434";
      "OPENAI_API_KEY" = "";
      "PGID" = "1000";
      "PUID" = "1000";
      "RESEARCH_LLM_ENDPOINT" = "";
      "SEARXNG_INSTANCE" = "http://searxng:8080";
      "SECURE_COOKIES" = "false";
      "SERPER_API_KEY" = "";
      "TAVILY_API_KEY" = "";
    };
    volumes = [
      "/home/seth/workspace/odysseus/data:/app/data:rw,z"
      "/home/seth/workspace/odysseus/data/huggingface:/app/.cache/huggingface:rw,z"
      "/home/seth/workspace/odysseus/data/local:/app/.local:rw,z"
      "/home/seth/workspace/odysseus/data/ssh:/app/.ssh:rw,z"
      "/home/seth/workspace/odysseus/logs:/app/logs:rw,z"
    ];
    ports = [
      "127.0.0.1:7000:7000/tcp"
    ];
    dependsOn = [
      "odysseus-chromadb"
      "odysseus-searxng"
    ];
    log-driver = "journald";
    extraOptions = [
      "--add-host=host.docker.internal:172.30.0.1"
      "--device=nvidia.com/gpu=all"
      "--network-alias=odysseus"
      "--network=odysseus_default"
    ];
  };
  systemd.services."docker-odysseus-odysseus" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-odysseus_default.service"
    ];
    requires = [
      "docker-network-odysseus_default.service"
    ];
    partOf = [
      "docker-compose-odysseus-root.target"
    ];
    wantedBy = [
      "docker-compose-odysseus-root.target"
    ];
  };
  virtualisation.oci-containers.containers."odysseus-searxng" = {
    image = "docker.io/searxng/searxng:2026.5.31-7159b8aed";
    entrypoint = "/bin/sh";
    cmd = [ "-c" ''
      set -eu
      if [ ! -s /etc/searxng/settings.yml ] || grep -q 'odysseus-local-searxng-json-2026-05-30\|__SEARXNG_SECRET__' /etc/searxng/settings.yml; then
        secret="''${SEARXNG_SECRET:-}"
        if [ -z "$secret" ]; then
          secret="$(python -c 'import secrets; print(secrets.token_urlsafe(48))')"
        fi
        sed "s|__SEARXNG_SECRET__|$secret|g" /tmp/searxng-settings.yml.template > /etc/searxng/settings.yml
      fi
      exec /usr/local/searxng/entrypoint.sh
    '' ];
    environment = {
      "SEARXNG_BASE_URL" = "http://localhost:8080/";
      "SEARXNG_SECRET" = "";
    };
    volumes = [
      "/home/seth/workspace/odysseus/config/searxng/settings.yml:/tmp/searxng-settings.yml.template:ro,z"
      "odysseus_searxng-data:/etc/searxng:rw"
    ];
    ports = [
      "127.0.0.1:8080:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=CHOWN"
      "--cap-add=DAC_OVERRIDE"
      "--cap-add=SETGID"
      "--cap-add=SETUID"
      "--cap-drop=ALL"
      "--health-cmd=python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8080/', timeout=5).read(1)\""
      "--health-interval=5s"
      "--health-retries=20"
      "--health-start-period=10s"
      "--health-timeout=6s"
      "--network-alias=searxng"
      "--network=odysseus_default"
    ];
  };
  systemd.services."docker-odysseus-searxng" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-odysseus_default.service"
      "docker-volume-odysseus_searxng-data.service"
    ];
    requires = [
      "docker-network-odysseus_default.service"
      "docker-volume-odysseus_searxng-data.service"
    ];
    partOf = [
      "docker-compose-odysseus-root.target"
    ];
    wantedBy = [
      "docker-compose-odysseus-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-odysseus_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f odysseus_default";
    };
    script = ''
      docker network inspect odysseus_default || docker network create \
      --subnet=172.30.0.0/24 \
      --gateway=172.30.0.1 \
      odysseus_default
    '';
    partOf = [ "docker-compose-odysseus-root.target" ];
    wantedBy = [ "docker-compose-odysseus-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-odysseus_chromadb-data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect odysseus_chromadb-data || docker volume create odysseus_chromadb-data
    '';
    partOf = [ "docker-compose-odysseus-root.target" ];
    wantedBy = [ "docker-compose-odysseus-root.target" ];
  };
  systemd.services."docker-volume-odysseus_ntfy-cache" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect odysseus_ntfy-cache || docker volume create odysseus_ntfy-cache
    '';
    partOf = [ "docker-compose-odysseus-root.target" ];
    wantedBy = [ "docker-compose-odysseus-root.target" ];
  };
  systemd.services."docker-volume-odysseus_searxng-data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect odysseus_searxng-data || docker volume create odysseus_searxng-data
    '';
    partOf = [ "docker-compose-odysseus-root.target" ];
    wantedBy = [ "docker-compose-odysseus-root.target" ];
  };

  # Builds
  systemd.services."docker-build-odysseus-odysseus" = {
    path = [ pkgs.docker pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /home/seth/workspace/odysseus
      docker build -t compose2nix/odysseus-odysseus .
    '';
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-odysseus-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
